### ISSUE TITLE
Translate by selecting text and pressing a key does not work with resistFingerprinting enabled

### ISSUE THREAD

**Issue by shvchk** [flytaly/multitran-extension#1]
Translate by just selecting text does work (i.e. when no modifier keys are enabled). But when some modifier key is enabled (e.g. Ctrl) it does not work.

If it's not possible to fix this, please consider adding a popup button on text selection, like [Simple Translate](https://addons.mozilla.org/en-US/firefox/addon/simple-translate) addon does. Or right click menu item.

Environment: Ubuntu 20.10, KDE Plasma, Firefox 82, privacy.resistFingerprinting = true

And thanks for this awesome addon btw : )

**Comment by flytaly** [comment]
I added item to the context menu as you requested.

As for shortcuts, yeah, for some reason when resistFingerprinting is enabled single `shift`, `alt` and `control` don't trigger JavaScript keyboard event.  You can check it [here](https://keycode.info).

But it's still possible to use them with different keys, so I added the ability to create a shortcut with an additional letter, number of F-key. 
The only caveat is that with `resistFingerprinting` non-English letters won't work but you still can use numbers and F1-F12 (for example, something like `Shift+2` should work in any keyboard layout).

**Comment by shvchk** [comment]
Ah, right, seems like a Firefox limitation. `F2` works for me, thank you!
