### ISSUE TITLE
Add more languages in menu?

### ISSUE THREAD

**Issue by srustamo** [flytaly/multitran-extension#17]
I would like to add the Tajik to Russian pair. Is it possible?

**Comment by flytaly** [comment]
Do you mean in **context** menu? I can add it, but it will be nested, like with the markdown extension of screenshot.

![image](https://github.com/flytaly/multitran-extension/assets/1577569/132368e1-44eb-44cc-8631-90d52908c3ef)

**Comment by flytaly** [comment]
Oh, I got it. There is no such pair at all, because it didn't exist when I made the extension. I need to update it then.

**Comment by flytaly** [comment]
V2.1.0 is available in store.

Select option "Enable all language pairs"

![image](https://github.com/flytaly/multitran-extension/assets/1577569/1a443b2f-9709-4327-b241-e651fdf2deb9)
