### ISSUE TITLE
z-index of a translation popup is too low

### ISSUE THREAD

**Issue by rand256** [flytaly/multitran-extension#2]
Changeset 3f216f2 among other things changed z-index property for `#translate-popup-content` from 9999 to 50, but I occasionally use this extension on a site that itself utilizes z-index property in range 1-500 for its own content. This way translation popup is now often hidden behind the site ​layout making the extension completely useless since a translation in most cases now can't be read at all.

And it seems that I can't even quick-hack it by increasing z-index of a popup with some CSS overriding extensions due to its shadow root.

**Comment by flytaly** [comment]
Yeah, 50 is the maximum default value in Tailwind, so I overlooked it.
Original 9999 is restored now. Update should be available in Chrome after the review (from hours to couple day).
